---
  - hosts: all
    become: true
    gather_facts: true
    roles:
      - role: misc
      - role: postgres
      - role: vault
      - role: concourse
    vars_prompt:
      - name: "external_ip"
        prompt: "External IP address of your machine"
        private: false
      - name: "concourse_username"
        prompt: "Concourse username"
        private: false
      - name: "concourse_password"
        prompt: "Concourse password"
    vars:
      shared:
        secret_repo: /opt/deployment-secrets
        vault_address: 127.0.0.1:8200
      